/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sysop.forms;

import com.sysop.dao.ConexaoBD;
import com.sysop.objects.Usuario;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author yakko
 */
public class CadastroUsuarioForm extends javax.swing.JFrame {
     private JFrame janelaAtiva;
      private Usuario usuario;

    /**
     * Creates new form CadastroUsuario
     */
    public CadastroUsuarioForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caEmail = new javax.swing.JTextField();
        caNome = new javax.swing.JTextField();
        caCPF = new javax.swing.JTextField();
        caSenha = new javax.swing.JPasswordField();
        Voltarbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SalvarButton = new javax.swing.JButton();
        elab = new javax.swing.JLabel();
        caFuncao = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        caEmail.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));
        caEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                caEmailKeyPressed(evt);
            }
        });

        caNome.setBorder(javax.swing.BorderFactory.createTitledBorder("Username"));
        caNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caNomeActionPerformed(evt);
            }
        });
        caNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                caNomeKeyPressed(evt);
            }
        });

        caCPF.setBorder(javax.swing.BorderFactory.createTitledBorder("CPF"));
        caCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                caCPFKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caCPFKeyReleased(evt);
            }
        });

        caSenha.setBorder(javax.swing.BorderFactory.createTitledBorder("Password"));

        Voltarbutton.setText("Voltar");
        Voltarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarbuttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Cadastro Usuario");

        SalvarButton.setText("Cadastrar");
        SalvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarButtonActionPerformed(evt);
            }
        });

        elab.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        elab.setForeground(new java.awt.Color(255, 0, 0));

        caFuncao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aluno", "Professor", "Gestor" }));
        caFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caFuncaoActionPerformed(evt);
            }
        });

        jLabel3.setText("Função");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caNome, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(184, 184, 184))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(caCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(caEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(elab, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(caFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(caSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(6, 6, 6))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(SalvarButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Voltarbutton)
                            .addContainerGap()))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(caNome, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(elab, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalvarButton)
                    .addComponent(Voltarbutton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarbuttonActionPerformed
       if (this.janelaAtiva != null) {
            this.janelaAtiva.dispose();
        }
        this.janelaAtiva = new GestorForm(this.usuario);
        this.janelaAtiva.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VoltarbuttonActionPerformed

    private void caCPFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caCPFKeyReleased
        // TODO add your handling code here:
        caCPF.setText(maxlength(caCPF.getText()));
    }//GEN-LAST:event_caCPFKeyReleased

    private void caEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caEmailKeyPressed
        // TODO add your handling code here:
        String PATTERN = "^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@" + "[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$";
        Pattern patt = Pattern.compile(PATTERN);
        String cEmail = caEmail.getText();
        Matcher match = patt.matcher(cEmail);
        if (!match.matches()) {
            elab.setText("usuario@email.com");
        } else {
            elab.setText(null);
        }
    }//GEN-LAST:event_caEmailKeyPressed

    private void caNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caNomeKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
            caNome.setEditable(true);
        } else {
            caNome.setEditable(false);
        }
    }//GEN-LAST:event_caNomeKeyPressed

    private void caCPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caCPFKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            caCPF.setEditable(false);
        } else {
            caCPF.setEditable(true);
        }
    }//GEN-LAST:event_caCPFKeyPressed

    private void SalvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarButtonActionPerformed
        // TODO add your handling code here:
        String cNome = caNome.getText();
        String cCPF = caCPF.getText();
        String cSenha = new String(caSenha.getPassword());
        String cEmail = caEmail.getText();
        String cFuncao = caFuncao.getSelectedItem().toString();
        String labelEmail = elab.getText();

        if (cNome.isEmpty() || cCPF.isEmpty() || cSenha.isEmpty() || cEmail.isEmpty() || cFuncao.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Campo vazio", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (labelEmail != null) {
            JOptionPane.showMessageDialog(this, "E-mail inválido", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String verficarSenha = "^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[$*&@#])[0-9a-zA-Z$*&@#]{8,}$";
        Pattern senhaPatt = Pattern.compile(verficarSenha);
        Matcher SenhaMatch = senhaPatt.matcher(cSenha);
        if (!SenhaMatch.matches()) {
            JOptionPane.showMessageDialog(this, "A senha deve conter no mínimo 8 caracteres, 1 letra maiúscula, 1 número e 1 símbolo", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

    // CONEXÃO AO BANCO DE DADOS
        String sql = "INSERT INTO usuario (nome, cpf, senha, email, funcao) VALUES(?, ?, ?, ?, ?) ";
        try (Connection conn = ConexaoBD.obterConexao(); PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, cNome);
            ps.setString(2, cCPF);
            ps.setString(3, cSenha);
            ps.setString(4, cEmail);
            ps.setString(5, cFuncao);

            int k = ps.executeUpdate();

            if (k == 1) {
                JOptionPane.showMessageDialog(this, "You have successfully registered!!!");
                caNome.setText("");
                caCPF.setText("");
                caSenha.setText("");
                caEmail.setText("");
                caFuncao.setSelectedItem("");
            }
        } catch (Exception ex) {
            Logger.getLogger(CadastroUsuarioForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SalvarButtonActionPerformed

    private void caFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caFuncaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caFuncaoActionPerformed

    private void caNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caNomeActionPerformed

    /**
     * @param args the command line arguments
     */

    public static String maxlength(String str) {
        String valor = "";
        if (str.length() > 11) {
            valor = str.substring(0, 11);
            str = valor;
        }
        return str;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SalvarButton;
    private javax.swing.JButton Voltarbutton;
    private javax.swing.JTextField caCPF;
    private javax.swing.JTextField caEmail;
    private javax.swing.JComboBox<String> caFuncao;
    private javax.swing.JTextField caNome;
    private javax.swing.JPasswordField caSenha;
    private javax.swing.JLabel elab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
