package com.sysop.forms;

import com.sysop.objects.Usuario;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 823134667
 */
public class GestorForm extends javax.swing.JFrame {
    
    private Usuario usuario;
    private JFrame janelaAtiva;

    /**
     * Creates new form AçõesGestor
     */
    public GestorForm(Usuario usuario) {
        initComponents();
        this.janelaAtiva = null;
        this.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FuncaoLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        CadMateriaButton = new javax.swing.JButton();
        CadUsuarioButton = new javax.swing.JButton();
        CadTurmaButton = new javax.swing.JButton();
        AlterarCadButton = new javax.swing.JButton();
        GabaritoButton = new javax.swing.JButton();
        CadPerguntasButton = new javax.swing.JButton();
        CadRespostasButton = new javax.swing.JButton();
        ExcluirButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        FuncaoLabel.setText("Funções Gestor");

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CadMateriaButton.setText("Cadastro de Materia");
        CadMateriaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CadMateriaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadMateriaButtonActionPerformed(evt);
            }
        });

        CadUsuarioButton.setText("Cadastro de Usuario");
        CadUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadUsuarioButtonActionPerformed(evt);
            }
        });

        CadTurmaButton.setText("Cadastro de Turma");
        CadTurmaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadTurmaButtonActionPerformed(evt);
            }
        });

        AlterarCadButton.setText("Alterar Cadastro");
        AlterarCadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarCadButtonActionPerformed(evt);
            }
        });

        GabaritoButton.setText("Gabarito");

        CadPerguntasButton.setText("Cadastro Perguntas");
        CadPerguntasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadPerguntasButtonActionPerformed(evt);
            }
        });

        CadRespostasButton.setText("Cadastro Respostas");
        CadRespostasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadRespostasButtonActionPerformed(evt);
            }
        });

        ExcluirButton.setText("Exluir Cadastro");
        ExcluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 298, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(FuncaoLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GabaritoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(ExcluirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(CadTurmaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AlterarCadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CadUsuarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CadMateriaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(28, 28, 28)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CadRespostasButton, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(CadPerguntasButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(FuncaoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CadMateriaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CadUsuarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CadPerguntasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CadRespostasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadTurmaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AlterarCadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GabaritoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExcluirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadMateriaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadMateriaButtonActionPerformed
        // TODO add your handling code here:
        if (this.janelaAtiva != null) {
            this.janelaAtiva.dispose();
        }
        this.janelaAtiva = new CadastroDisciplinaForm(this.usuario);
        this.janelaAtiva.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CadMateriaButtonActionPerformed

    private void CadUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadUsuarioButtonActionPerformed
        // TODO add your handling code here:
        if (this.janelaAtiva != null) {
            this.janelaAtiva.dispose();
        }
        this.janelaAtiva = new CadastroUsuarioForm();
        this.janelaAtiva.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CadUsuarioButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CadTurmaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadTurmaButtonActionPerformed
   
       if (this.janelaAtiva != null) {
            this.janelaAtiva.dispose();
        }
        this.janelaAtiva = new CadastroTurmaForm(this.usuario);
        this.janelaAtiva.setVisible(true);
         this.dispose(); 
    }//GEN-LAST:event_CadTurmaButtonActionPerformed

    private void CadPerguntasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadPerguntasButtonActionPerformed
        // TODO add your handling code here:
        if (this.janelaAtiva != null) {
            this.janelaAtiva.dispose();
        }
        this.janelaAtiva = new CadastroPerguntasForm();
        this.janelaAtiva.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_CadPerguntasButtonActionPerformed

    private void CadRespostasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadRespostasButtonActionPerformed
        if (this.janelaAtiva != null) {
            this.janelaAtiva.dispose();
        }
        this.janelaAtiva = new CadastroRespostas();
        this.janelaAtiva.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CadRespostasButtonActionPerformed

    private void AlterarCadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarCadButtonActionPerformed
     if (this.janelaAtiva != null) {
            this.janelaAtiva.dispose();
        }
        this.janelaAtiva = new AlterarCadastro();
        this.janelaAtiva.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AlterarCadButtonActionPerformed

    private void ExcluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirButtonActionPerformed
        if (this.janelaAtiva != null) {
        this.janelaAtiva.dispose();
        }
        this.janelaAtiva = new DeletarUsuario();
        this.janelaAtiva.setVisible(true);
        this.dispose();
       
    
    }//GEN-LAST:event_ExcluirButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlterarCadButton;
    private javax.swing.JButton CadMateriaButton;
    private javax.swing.JButton CadPerguntasButton;
    private javax.swing.JButton CadRespostasButton;
    private javax.swing.JButton CadTurmaButton;
    private javax.swing.JButton CadUsuarioButton;
    private javax.swing.JButton ExcluirButton;
    private javax.swing.JLabel FuncaoLabel;
    private javax.swing.JButton GabaritoButton;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
