/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sysop.forms;

import com.sysop.dao.ConexaoBD;
import com.sysop.objects.Usuario;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.Random;

public class ProvaForm extends javax.swing.JFrame {
    
    
    
    public ProvaForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        SairButton = new javax.swing.JButton();
        enviar_prova = new javax.swing.JButton();
        iniciar_prova = new javax.swing.JButton();
        proxima = new javax.swing.JButton();
        proxima.setVisible(false);
        enunciado = new javax.swing.JLabel();
        Alternativas = new javax.swing.JComboBox<>();
        questao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SairButton.setText("Sair");
        SairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairButtonActionPerformed(evt);
            }
        });

        enviar_prova.setText("Terminar");
        enviar_prova.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enviar_provaMouseClicked(evt);
            }
        });
        enviar_prova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviar_provaActionPerformed(evt);
            }
        });

        iniciar_prova.setText("Iniciar");
        iniciar_prova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciar_provaActionPerformed(evt);
            }
        });

        proxima.setText("Proxima");
        proxima.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proximaMouseClicked(evt);
            }
        });
        proxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximaActionPerformed(evt);
            }
        });

        enunciado.setText("Aperte em \"Iniciar\" para iniciar a prova . ");

        Alternativas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "A", "B", "C", "D" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(Alternativas, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(proxima, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(280, 280, 280))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(questao)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(iniciar_prova)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(enviar_prova)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(SairButton)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(enunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 979, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SairButton)
                    .addComponent(enviar_prova)
                    .addComponent(iniciar_prova))
                .addGap(14, 14, 14)
                .addComponent(questao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proxima, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Alternativas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private String enunciadot;
    private int idEnunciadot;
    private int idProva;
    private int contador = 0;   
   
    public int getidProva(){
        
        return idProva;
        
    }
    public void setidProva(int idProva){
        
        this.idProva = idProva;
        
    }
    
    public String getEnunciado(){
        
        return enunciadot;
    }
    
    public void setEnunciado(){
        
        this.enunciadot = enunciadot;
        
    }
    
    public int getIdEnunciado(){
        
        return idEnunciadot;
        
    }
    
    public void setIdEnunciado(){
        
        this.idEnunciadot = idEnunciadot;
        
    }
    
    private void carregar  (){
        Random aleatorio = new Random();
        int idpergunta = aleatorio.nextInt((8+1)+1)+8;
        
        String sql = "SELECT * FROM pergunta WHERE ID_Perguntas = ?";
        try (Connection conn = ConexaoBD.obterConexao(); PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setInt(1, idpergunta);
            
            int k = ps.executeUpdate();

            if (k == 1) {
                enunciado.setText(sql);
                
            }    
        }catch (Exception ex) {
            ex.printStackTrace();
        }
        
        
        
    }
    
    private void SairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairButtonActionPerformed
      this.dispose ();
    }//GEN-LAST:event_SairButtonActionPerformed

    private void enviar_provaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviar_provaActionPerformed
       
    }//GEN-LAST:event_enviar_provaActionPerformed

    private void iniciar_provaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciar_provaActionPerformed
        Random aleatorio = new Random();
        int id = aleatorio.nextInt((999999+111111)+1)+111111;
        setidProva(id);
        int data = 20230612 ;
        // CONEXÃO AO BANCO DE DADOS
        String sql = "INSERT INTO Prova (idProva, data) VALUES(?, ?) ";
        try (Connection conn = ConexaoBD.obterConexao(); PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setInt(1, id);
            ps.setInt(2, data);
            

            int k = ps.executeUpdate();

            if (k == 1) {
                JOptionPane.showMessageDialog(this, "Iniciando a prova");
                contador = 1;
                questao.setText("Questão " + contador );
                proxima.setVisible(true);
                iniciar_prova.setVisible(false);
                
                enunciado.setText("Dada a equação ax^2 + bx + c = 0. Qual é a fórmula geral para encontrar o valor de x em termos de a, b e c?\n" +
"\n" +
"a) x = (-b ± √(b^2 - 4ac)) / (2a)"+ "\n" +" b) x = (-b ± √(b^2 + 4ac)) / (2a) c) x = (b ± √(b^2 - 4ac)) / (2a) d) x = (-b ± √(b^2 - 4ac)) / a");
                carregar();
                
                
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        
    }//GEN-LAST:event_iniciar_provaActionPerformed

    private void proximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximaActionPerformed
        
    }//GEN-LAST:event_proximaActionPerformed
    
    
    
    private void proximaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proximaMouseClicked
        carregar();
        if(contador <= 4){
            contador = contador +1;
            questao.setText("Questão " + contador );
            enunciado.setText("Questão não cadastrada");
            
        }else{
            JOptionPane.showMessageDialog(this, "Prova Finalizada");
            proxima.setVisible(false);
            enunciado.setText("Aperte em \"Terminar\" para enviar a prova ");
        }
        
        
    }//GEN-LAST:event_proximaMouseClicked

    private void enviar_provaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviar_provaMouseClicked
        Random aleatorio = new Random();
        int id = aleatorio.nextInt((999+111)+1)+111;
        int idaluno = 3;
        String resultadoss = "3";
        
        String sql = "INSERT INTO provarealizada (ID_ProvasRealizadas,ID_Aluno,Resultados,ID_Prova ) VALUES(?, ?, ?, ?) ";
        try (Connection conn = ConexaoBD.obterConexao(); PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setInt(1, id);
            ps.setInt(2, idaluno);
            ps.setString(3,resultadoss);
            ps.setInt(4, idProva);
            int k = ps.executeUpdate();

            if (k == 1) {
                JOptionPane.showMessageDialog(this, "prova Enviada" );
                    
                
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        JOptionPane.showMessageDialog(this, "prova Enviada" );
        this.dispose ();
    
    }//GEN-LAST:event_enviar_provaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Alternativas;
    private javax.swing.JButton SairButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel enunciado;
    private javax.swing.JButton enviar_prova;
    private javax.swing.JButton iniciar_prova;
    private javax.swing.JButton proxima;
    private javax.swing.JLabel questao;
    // End of variables declaration//GEN-END:variables
}
